"""
RasFixit - Automated Geometry Repair for HEC-RAS Models.

This module provides automated fix capabilities for common HEC-RAS geometry issues.
All methods are static and follow ras-commander conventions.

Supported Fixes:
    General-purpose (any model version):
    - Blocked Obstruction Overlaps: Resolves overlapping obstructions using max elevation
    - HTAB Starting Elevation: Fixes starting_el < invert issues

    Version upgrade (HEC-RAS 4.x → 6.x):
    - Bank Station Normalization: Re-writes sta/elev with normalized fixed-width formatting
    - Ineffective Flow Areas: Replaces right_station=0 sentinels with actual rightmost station
    - Manning's n Repair: Reconstructs missing data or snaps misaligned breakpoints to banks

Engineering Review Requirements:
    All fixes generated by RasFixit modify hydraulic model geometry.
    Results should be reviewed by a licensed professional engineer
    before accepting changes to production models.

    The visualization output provides an audit trail showing:
    - Original obstruction configuration
    - Fixed obstruction configuration
    - Algorithm decisions made

Example:
    >>> from ras_commander import RasFixit
    >>> results = RasFixit.fix_blocked_obstructions("model.g01", visualize=True)
    >>> print(f"Fixed {results.total_xs_fixed} cross sections")
"""

import re
import shutil
from pathlib import Path
from typing import Union, Optional, List
from datetime import datetime

from ..Decorators import log_call
from ..LoggingConfig import get_logger
from .results import FixResults, FixMessage, FixAction
from .obstructions import (
    BlockedObstruction,
    create_elevation_envelope,
    has_overlaps,
)

logger = get_logger(__name__)


class RasFixit:
    """
    Automated geometry repair for HEC-RAS models.

    All methods are static and designed for geometry file path input.
    This follows the ras-commander convention of static classes.

    Integration with RasCheck:
        RasCheck.check_xs() detects obstruction issues (XS_BO_01, XS_BO_02)
        RasFixit.fix_blocked_obstructions() repairs those issues

        RasCheck.check_htab_params() detects HTAB issues (HTAB_SE_01)
        RasFixit.fix_htab_starting_elevations() repairs those issues

    Example:
        >>> from ras_commander import RasFixit, RasCheck
        >>>
        >>> # First detect issues
        >>> check_results = RasCheck.check_xs(geom_hdf)
        >>> obstruction_issues = [m for m in check_results.messages
        ...                       if m.message_id.startswith('XS_BO')]
        >>>
        >>> if obstruction_issues:
        ...     # Then fix them
        ...     fix_results = RasFixit.fix_blocked_obstructions(
        ...         "model.g01", visualize=True
        ...     )
        ...     print(f"Fixed {fix_results.total_xs_fixed} cross sections")
    """

    @staticmethod
    @log_call
    def fix_blocked_obstructions(
        geom_path: Union[str, Path],
        backup: bool = True,
        visualize: bool = False,
        dry_run: bool = False
    ) -> FixResults:
        """
        Fix overlapping blocked obstructions in a geometry file.

        Uses max-elevation envelope algorithm to resolve overlaps while
        preserving conservative hydraulic behavior. Creates verification
        outputs for engineering review.

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)
            backup: Create timestamped backup before modification (default True)
            visualize: Generate before/after PNG comparisons (default False)
            dry_run: Detect issues without modifying file (default False)

        Returns:
            FixResults with messages for each fixed cross section.
            Use results.to_dataframe() for pandas DataFrame output.

        Raises:
            FileNotFoundError: If geometry file doesn't exist.

        Example:
            >>> results = RasFixit.fix_blocked_obstructions(
            ...     "BaldEagle.g01",
            ...     backup=True,
            ...     visualize=True
            ... )
            >>> for msg in results.messages:
            ...     print(f"RS {msg.station}: {msg.action.value}")

        Note:
            The algorithm uses maximum elevations in overlap zones, which is
            hydraulically conservative (preserves flow restrictions).
            All changes should be reviewed by a licensed professional engineer.
        """
        geom_path = Path(geom_path)
        if not geom_path.exists():
            raise FileNotFoundError(f"Geometry file not found: {geom_path}")

        results = FixResults()

        # Create backup if requested and not dry run
        if backup and not dry_run:
            backup_path = RasFixit._create_backup(geom_path)
            results.backup_path = backup_path
            logger.info(f"Created backup: {backup_path}")

        from ..geom.GeomCrossSection import GeomCrossSection

        xs_df = GeomCrossSection.get_cross_sections(geom_path)
        results.total_xs_checked = len(xs_df)

        # Setup visualization folder if needed
        viz_folder = None
        if visualize and not dry_run:
            viz_folder = RasFixit._create_viz_folder(geom_path)
            results.visualization_folder = viz_folder
            logger.info(f"Saving visualizations to: {viz_folder}")

        obs_df = GeomCrossSection.get_blocked_obstructions(geom_path)
        if obs_df.empty:
            return results

        for xs_id, group in obs_df.groupby("xs_id", sort=False):
            original = [
                BlockedObstruction(row.start_sta, row.end_sta, row.elevation)
                for row in group.itertuples()
            ]

            if len(original) < 2 or not has_overlaps(original):
                continue

            fixed = create_elevation_envelope(original)
            first = group.iloc[0]
            river = str(first["River"])
            reach = str(first["Reach"])
            rs_id = str(first["RS"])

            msg = FixMessage(
                message_id="FX_BO_01",
                fix_type="OBSTRUCTION",
                river=river,
                reach=reach,
                station=rs_id,
                action=FixAction.OVERLAP_RESOLVED,
                message=(
                    f"Resolved {len(original)} overlapping obstructions to "
                    f"{len(fixed)} non-overlapping"
                ),
                original_count=len(original),
                fixed_count=len(fixed),
                original_data=[o.to_tuple() for o in original],
                fixed_data=[o.to_tuple() for o in fixed],
            )

            logger.debug(f"RS {rs_id}: {len(original)} -> {len(fixed)} obstructions")

            if viz_folder and not dry_run:
                viz_path = viz_folder / f"RS_{rs_id.replace('.', '_')}.png"
                msg.visualization_path = viz_path
                RasFixit._visualize(original, fixed, rs_id, viz_path)

            results.messages.append(msg)
            results.total_xs_fixed += 1

            if not dry_run:
                GeomCrossSection.set_blocked_obstructions(
                    geom_path,
                    xs_id,
                    fixed,
                    create_backup=False,
                )

        if not dry_run and results.total_xs_fixed > 0:
            logger.info(
                f"Fixed {results.total_xs_fixed} cross sections in {geom_path.name}"
            )

        return results

    @staticmethod
    @log_call
    def detect_obstruction_overlaps(geom_path: Union[str, Path]) -> FixResults:
        """
        Detect overlapping blocked obstructions without modifying the file.

        This is equivalent to fix_blocked_obstructions(dry_run=True).
        Useful for pre-flight checks before applying fixes.

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)

        Returns:
            FixResults with detection messages (no modifications made).

        Example:
            >>> results = RasFixit.detect_obstruction_overlaps("model.g04")
            >>> print(f"Found {results.total_xs_fixed} cross sections with overlaps")
        """
        return RasFixit.fix_blocked_obstructions(
            geom_path, backup=False, visualize=False, dry_run=True
        )

    @staticmethod
    def _create_backup(geom_path: Path) -> Path:
        """Create timestamped backup of geometry file."""
        timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
        backup_path = geom_path.parent / f"{geom_path.name}.backup_{timestamp}"
        shutil.copy2(geom_path, backup_path)
        return backup_path

    @staticmethod
    def _create_viz_folder(geom_path: Path) -> Path:
        """Create visualization output folder."""
        # Extract geometry number
        g_match = re.search(r'\.g(\d+)(?:\.|$)', geom_path.name, re.IGNORECASE)
        g_num = g_match.group(1) if g_match else "XX"

        # Extract project name (everything before .g##)
        project_name = re.sub(r'\.g\d+.*', '', geom_path.name)

        # Create folder name: ProjectName_g##_Obstructions_Fixed
        dir_name = f"{project_name}_g{g_num}_Obstructions_Fixed"

        viz_folder = geom_path.parent / dir_name
        viz_folder.mkdir(exist_ok=True)

        return viz_folder

    @staticmethod
    def _visualize(
        original: List[BlockedObstruction],
        fixed: List[BlockedObstruction],
        rs_id: str,
        save_path: Path
    ) -> bool:
        """
        Generate before/after visualization PNG.

        Lazy loads matplotlib to avoid import overhead when visualization
        is not requested.

        Args:
            original: Original overlapping obstructions.
            fixed: Fixed non-overlapping obstructions.
            rs_id: River station identifier.
            save_path: Output PNG path.

        Returns:
            True if visualization was created, False otherwise.
        """
        from .visualization import visualize_obstruction_fix
        return visualize_obstruction_fix(original, fixed, rs_id, save_path)

    # =========================================================================
    # HTAB (Hydraulic Table) Fixes
    # =========================================================================

    @staticmethod
    @log_call
    def fix_htab_starting_elevations(
        geom_path: Union[str, Path],
        backup: bool = True,
        dry_run: bool = False,
        margin: float = 0.0
    ) -> FixResults:
        """
        Fix HTAB starting elevation issues in a geometry file.

        HTAB (Hydraulic Table) starting elevation must be >= cross section invert.
        This is a hard HEC-RAS requirement - models with starting_el < invert will
        fail during preprocessing (common issue when upgrading from older HEC-RAS versions).

        This method identifies all cross sections where starting_el < invert and
        automatically corrects them by setting starting_el = invert + margin.

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)
            backup: Create timestamped backup before modification (default True)
            dry_run: Detect issues without modifying file (default False)
            margin: Additional margin above invert for starting elevation (default 0.0 ft)
                   Use small positive value (e.g., 0.1) for extra safety margin.

        Returns:
            FixResults with messages for each fixed cross section.
            - total_xs_checked: Number of XS with HTAB parameters examined
            - total_xs_fixed: Number of XS with starting_el corrected
            - messages: List of FixMessage objects with before/after values
            Use results.to_dataframe() for pandas DataFrame output.

        Raises:
            FileNotFoundError: If geometry file doesn't exist.

        Example:
            >>> from ras_commander import RasFixit
            >>>
            >>> # Fix all HTAB starting elevation issues
            >>> results = RasFixit.fix_htab_starting_elevations("model.g01")
            >>> print(f"Fixed {results.total_xs_fixed} cross sections")
            >>>
            >>> # Detection only (no modifications)
            >>> results = RasFixit.fix_htab_starting_elevations(
            ...     "model.g01", dry_run=True
            ... )
            >>> print(f"Found {results.total_xs_fixed} cross sections with issues")
            >>>
            >>> # View details
            >>> df = results.to_dataframe()
            >>> print(df[['river', 'reach', 'station', 'message']])

        Note:
            This fix is required after HEC-RAS version upgrades or when importing
            geometry from external sources. HEC-RAS will fail with an error during
            geometry preprocessing if starting_el < invert.

        Integration with RasCheck:
            RasCheck.check_htab_params() detects HTAB_SE_01 errors (starting_el < invert)
            RasFixit.fix_htab_starting_elevations() repairs those issues

        See Also:
            - GeomCrossSection.get_xs_htab_params(): Read HTAB parameters
            - GeomCrossSection.set_xs_htab_params(): Write HTAB parameters
            - RasCheck.check_htab_params(): Validate HTAB parameters
        """
        from ..geom.GeomCrossSection import GeomCrossSection

        geom_path = Path(geom_path)
        if not geom_path.exists():
            raise FileNotFoundError(f"Geometry file not found: {geom_path}")

        results = FixResults()

        # Create backup if requested and not dry run
        if backup and not dry_run:
            backup_path = RasFixit._create_backup(geom_path)
            results.backup_path = backup_path
            logger.info(f"Created backup: {backup_path}")

        try:
            # Get all cross sections from geometry file
            xs_df = GeomCrossSection.get_cross_sections(geom_path)
            # Filter to Type 1 (real cross sections) only - excludes lateral
            # structures (Type 6), bridges, culverts, etc. which lack #Sta/Elev data
            if 'Type' in xs_df.columns:
                xs_df = xs_df[xs_df['Type'] == 1].reset_index(drop=True)

            if xs_df.empty:
                logger.info(f"No cross sections found in {geom_path.name}")
                return results

            logger.info(f"Checking HTAB starting elevations for {len(xs_df)} cross sections")

            xs_to_fix = []  # List of dicts with fix info

            for _, row in xs_df.iterrows():
                river = row['River']
                reach = row['Reach']
                rs = row['RS']

                try:
                    # Get HTAB parameters for this XS
                    htab_params = GeomCrossSection.get_xs_htab_params(
                        geom_path, river, reach, rs
                    )

                    starting_el = htab_params.get('starting_el')
                    invert = htab_params.get('invert')

                    # Skip if no HTAB params or no starting elevation defined
                    if starting_el is None or invert is None:
                        continue

                    results.total_xs_checked += 1

                    # Check if starting_el < invert (ERROR condition)
                    if starting_el < invert:
                        corrected_starting_el = invert + margin
                        xs_to_fix.append({
                            'river': river,
                            'reach': reach,
                            'rs': rs,
                            'original_starting_el': starting_el,
                            'invert': invert,
                            'corrected_starting_el': corrected_starting_el,
                            'increment': htab_params.get('increment'),
                            'num_points': htab_params.get('num_points')
                        })

                        # Create fix message
                        msg = FixMessage(
                            message_id="FX_HTAB_01",
                            fix_type="HTAB",
                            river=river,
                            reach=reach,
                            station=str(rs),
                            action=FixAction.HTAB_STARTING_EL_FIXED,
                            message=(
                                f"HTAB starting elevation corrected from {starting_el:.2f} "
                                f"to {corrected_starting_el:.2f} (invert={invert:.2f})"
                            ),
                            original_data=[(starting_el, invert, 0.0)],
                            fixed_data=[(corrected_starting_el, invert, 0.0)]
                        )
                        results.messages.append(msg)

                        logger.debug(
                            f"{river}/{reach}/RS {rs}: starting_el {starting_el:.2f} -> "
                            f"{corrected_starting_el:.2f} (invert={invert:.2f})"
                        )

                except Exception as e:
                    logger.warning(f"Error checking HTAB for {river}/{reach}/RS {rs}: {e}")
                    continue

            results.total_xs_fixed = len(xs_to_fix)

            # Apply fixes if not dry run
            if not dry_run and xs_to_fix:
                logger.info(f"Applying fixes to {len(xs_to_fix)} cross sections")

                for xs_info in xs_to_fix:
                    try:
                        GeomCrossSection.set_xs_htab_params(
                            geom_path,
                            xs_info['river'],
                            xs_info['reach'],
                            xs_info['rs'],
                            starting_el=xs_info['corrected_starting_el'],
                            increment=xs_info['increment'],
                            num_points=xs_info['num_points']
                        )
                    except Exception as e:
                        logger.error(
                            f"Failed to fix HTAB for {xs_info['river']}/{xs_info['reach']}/"
                            f"RS {xs_info['rs']}: {e}"
                        )

                logger.info(
                    f"Fixed HTAB starting elevations for {len(xs_to_fix)} cross sections "
                    f"in {geom_path.name}"
                )
            elif dry_run and xs_to_fix:
                logger.info(
                    f"Dry run: Found {len(xs_to_fix)} cross sections with HTAB starting_el < invert"
                )

            # Add statistics
            results.statistics = {
                'total_xs_in_file': len(xs_df),
                'xs_with_htab': results.total_xs_checked,
                'xs_with_issues': results.total_xs_fixed,
                'margin_used': margin
            }

        except Exception as e:
            logger.error(f"Failed to fix HTAB starting elevations: {e}")
            raise

        return results

    @staticmethod
    @log_call
    def detect_htab_issues(geom_path: Union[str, Path]) -> FixResults:
        """
        Detect HTAB starting elevation issues without modifying the file.

        This is equivalent to fix_htab_starting_elevations(dry_run=True).
        Useful for pre-flight checks before applying fixes.

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)

        Returns:
            FixResults with detection messages (no modifications made).

        Example:
            >>> results = RasFixit.detect_htab_issues("model.g01")
            >>> print(f"Found {results.total_xs_fixed} cross sections with HTAB issues")
            >>> for msg in results.messages:
            ...     print(f"  {msg.river}/{msg.reach}/RS {msg.station}: {msg.message}")
        """
        return RasFixit.fix_htab_starting_elevations(
            geom_path, backup=False, dry_run=True
        )

    # ========== BANK STATION FIXES ==========

    @staticmethod
    @log_call
    def fix_bank_stations(
        geom_path: Union[str, Path],
        backup: bool = True,
        dry_run: bool = False,
        rs_list: Optional[List[str]] = None
    ) -> FixResults:
        """
        Fix bank station / station-elevation data for cross sections.

        **Version upgrade fix (HEC-RAS 4.x → 6.x).** Also safe as a general-purpose
        normalization pass on any model version.

        Re-writes station/elevation data through set_station_elevation() which
        normalizes fixed-width formatting (all values to {:8.2f}) and ensures
        bank stations appear as exact points via _interpolate_at_banks(). Existing
        points within 0.005 units of a bank station are snapped to the exact bank
        value rather than inserting a near-duplicate.

        HEC-RAS 6.x has stricter validation than 4.x for bank station matching.
        A round-trip rewrite normalizes the FORTRAN fixed-width format, resolving
        mismatches that are invisible to value-based comparisons.

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)
            backup: Create timestamped backup before modification (default True)
            dry_run: Detect issues without modifying file (default False)
            rs_list: Optional list of RS values to fix. If None, fixes all
                     Type 1 cross sections (full normalization).

        Returns:
            FixResults with messages for each cross section targeted.

        Raises:
            FileNotFoundError: If geometry file doesn't exist.

        Example:
            >>> # Fix specific cross sections from RAS error report
            >>> results = RasFixit.fix_bank_stations(
            ...     "model.g01",
            ...     rs_list=["76202", "70462", "68673"]
            ... )
            >>> print(f"Fixed {results.total_xs_fixed} cross sections")

        Note:
            This fix targets models upgraded from HEC-RAS 4.x to 6.x, but the
            normalization is also safe for any model version. All changes should
            be reviewed by a licensed professional engineer.
        """
        from ..geom.GeomCrossSection import GeomCrossSection

        geom_path = Path(geom_path)
        if not geom_path.exists():
            raise FileNotFoundError(f"Geometry file not found: {geom_path}")

        results = FixResults()

        # Create backup if requested and not dry run
        if backup and not dry_run:
            backup_path = RasFixit._create_backup(geom_path)
            results.backup_path = backup_path
            logger.info(f"Created backup: {backup_path}")

        try:
            # Get all cross sections
            xs_df_all = GeomCrossSection.get_cross_sections(geom_path)

            # Filter to Type 1 (natural cross sections only)
            xs_df = xs_df_all[xs_df_all['Type'] == 1]

            # Filter to specific RS values if provided
            if rs_list is not None:
                rs_set = set(str(r).strip() for r in rs_list)
                xs_df = xs_df[xs_df['RS'].apply(
                    lambda x: str(x).strip() in rs_set
                )]

            results.total_xs_checked = len(xs_df)
            xs_to_fix = []

            for _, row in xs_df.iterrows():
                river = row['River']
                reach = row['Reach']
                rs = str(row['RS'])

                try:
                    banks = GeomCrossSection.get_bank_stations(
                        geom_path, river, reach, rs
                    )
                    if banks is None:
                        continue

                    bank_left, bank_right = banks

                    msg = FixMessage(
                        message_id="FX_BK_01",
                        fix_type="BANK_STATION",
                        river=river,
                        reach=reach,
                        station=rs,
                        action=FixAction.BANK_STATION_REWRITTEN,
                        message=(
                            f"Rewriting sta/elev with normalized formatting. "
                            f"Banks: L={bank_left}, R={bank_right}"
                        )
                    )
                    results.messages.append(msg)
                    xs_to_fix.append((river, reach, rs, bank_left, bank_right))

                except Exception as e:
                    logger.warning(f"Error reading {river}/{reach}/RS {rs}: {e}")
                    continue

            # Apply fixes if not dry run
            if not dry_run and xs_to_fix:
                for river, reach, rs, bank_left, bank_right in xs_to_fix:
                    try:
                        sta_elev = GeomCrossSection.get_station_elevation(
                            geom_path, river, reach, rs
                        )
                        GeomCrossSection.set_station_elevation(
                            geom_path, river, reach, rs, sta_elev,
                            bank_left=bank_left, bank_right=bank_right
                        )
                        results.total_xs_fixed += 1
                        logger.debug(
                            f"Normalized {river}/{reach}/RS {rs}"
                        )
                    except Exception as e:
                        logger.error(
                            f"Failed to fix {river}/{reach}/RS {rs}: {e}"
                        )
            elif dry_run:
                results.total_xs_fixed = len(xs_to_fix)
                logger.info(
                    f"Dry run: {len(xs_to_fix)} cross sections to normalize"
                )

            results.statistics = {
                'total_xs_in_file': len(xs_df_all),
                'xs_targeted': results.total_xs_checked,
                'xs_fixed': len(xs_to_fix)
            }

        except Exception as e:
            logger.error(f"Failed to fix bank stations: {e}")
            raise

        return results

    @staticmethod
    @log_call
    def detect_bank_station_issues(
        geom_path: Union[str, Path]
    ) -> FixResults:
        """
        Detect bank station formatting issues without modifying the file (dry run).

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)

        Returns:
            FixResults with messages for each cross section that would be normalized.
        """
        return RasFixit.fix_bank_stations(geom_path, backup=False, dry_run=True)

    # ========== INEFFECTIVE FLOW AREA FIXES ==========

    @staticmethod
    @log_call
    def fix_ineffective_flow(
        geom_path: Union[str, Path],
        backup: bool = True,
        dry_run: bool = False,
        rs_list: Optional[List[str]] = None
    ) -> FixResults:
        """
        Fix malformed ineffective flow area data in HEC-RAS geometry files.

        **Version upgrade fix (HEC-RAS 4.x → 6.x).** Not applicable to models
        originally created in HEC-RAS 6.x.

        HEC-RAS 4.x accepted ``0`` as a sentinel station value meaning "extend
        to the cross section boundary." HEC-RAS 6.x treats ``0`` literally,
        creating backwards pairs (left_station > right_station) that fail
        data check validation with misleading "Bank station not in sta/elev
        data" cascade errors.

        This method scans all Type 1 cross sections for ``#XS Ineff=`` blocks
        where any triplet has ``right_station == 0`` AND ``left_station > 0``.
        The fix replaces ``right_station = 0`` with the actual rightmost station
        from the cross section's sta/elev data.

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)
            backup: Create timestamped backup before modification (default True)
            dry_run: Detect issues without modifying file (default False)
            rs_list: Optional list of RS values to check. If None, checks all
                     Type 1 cross sections.

        Returns:
            FixResults with messages for each modified cross section.

        Raises:
            FileNotFoundError: If geometry file doesn't exist.

        Example:
            >>> results = RasFixit.fix_ineffective_flow(
            ...     "model.g01",
            ...     backup=True
            ... )
            >>> print(f"Fixed {results.total_xs_fixed} cross sections")
            >>> for msg in results.messages:
            ...     print(f"  RS {msg.station}: {msg.message}")

        Note:
            This fix targets models upgraded from HEC-RAS 4.x to 6.x, or models
            converted from HEC-2. The right_station=0 sentinel pattern does not
            occur in models originally created in HEC-RAS 6.x. All changes should
            be reviewed by a licensed professional engineer.
        """
        from ..geom.GeomCrossSection import GeomCrossSection

        geom_path = Path(geom_path)
        if not geom_path.exists():
            raise FileNotFoundError(f"Geometry file not found: {geom_path}")

        results = FixResults()

        if backup and not dry_run:
            backup_path = RasFixit._create_backup(geom_path)
            results.backup_path = backup_path
            logger.info(f"Created backup: {backup_path}")

        try:
            xs_df_all = GeomCrossSection.get_cross_sections(geom_path)
            xs_df = xs_df_all[xs_df_all['Type'] == 1]

            if rs_list is not None:
                rs_set = set(str(r).strip() for r in rs_list)
                xs_df = xs_df[xs_df['RS'].apply(lambda x: str(x).strip() in rs_set)]

            results.total_xs_checked = len(xs_df)
            xs_to_fix = []

            for _, row in xs_df.iterrows():
                river = row['River']
                reach = row['Reach']
                rs = str(row['RS'])

                try:
                    ineff_df, fmt_flag, perm_flags = GeomCrossSection.get_ineffective_flow(
                        geom_path, river, reach, rs
                    )
                    if ineff_df is None:
                        continue

                    # Find pairs where right_station=0 and left_station > 0
                    # (backwards pair: 4.x sentinel -> 6.x takes 0 literally)
                    bad_mask = (ineff_df['right_station'] == 0) & (ineff_df['left_station'] > 0)
                    if not bad_mask.any():
                        continue

                    # Get rightmost station from sta/elev data
                    sta_elev = GeomCrossSection.get_station_elevation(
                        geom_path, river, reach, rs
                    )
                    rightmost = float(sta_elev['Station'].max())

                    bad_rows = ineff_df[bad_mask]
                    details = "; ".join(
                        f"pair({r['left_station']:.2f}->0) fixed to {rightmost:.2f}"
                        for _, r in bad_rows.iterrows()
                    )

                    msg = FixMessage(
                        message_id="FX_IF_01",
                        fix_type="INEFFECTIVE",
                        river=river,
                        reach=reach,
                        station=rs,
                        action=FixAction.INEFFECTIVE_FIXED,
                        message=(
                            f"right_station=0 replaced with rightmost sta {rightmost:.2f}. "
                            f"{details}"
                        ),
                        original_count=len(ineff_df),
                        fixed_count=len(ineff_df),
                        original_data=[
                            (r['left_station'], r['right_station'], r['elevation'])
                            for _, r in ineff_df.iterrows()
                        ]
                    )
                    results.messages.append(msg)
                    xs_to_fix.append(
                        (river, reach, rs, ineff_df.copy(), fmt_flag, perm_flags, rightmost)
                    )

                except Exception as e:
                    logger.warning(f"Error checking {river}/{reach}/RS {rs}: {e}")
                    continue

            if not dry_run and xs_to_fix:
                for river, reach, rs, ineff_df, fmt_flag, perm_flags, rightmost in xs_to_fix:
                    try:
                        fixed_df = ineff_df.copy()
                        bad_mask = (
                            (fixed_df['right_station'] == 0) & (fixed_df['left_station'] > 0)
                        )
                        fixed_df.loc[bad_mask, 'right_station'] = rightmost

                        GeomCrossSection.set_ineffective_flow(
                            geom_path, river, reach, rs,
                            fixed_df, fmt_flag, perm_flags
                        )
                        results.total_xs_fixed += 1
                        logger.debug(
                            f"Fixed ineffective flow for {river}/{reach}/RS {rs}: "
                            f"right_station=0 -> {rightmost:.2f}"
                        )

                        # Update message with fixed_data
                        for msg in results.messages:
                            if msg.station.strip() == rs.strip():
                                msg.fixed_data = [
                                    (r['left_station'], r['right_station'], r['elevation'])
                                    for _, r in fixed_df.iterrows()
                                ]
                                break

                    except Exception as e:
                        logger.error(f"Failed to fix {river}/{reach}/RS {rs}: {e}")

            elif dry_run:
                results.total_xs_fixed = len(xs_to_fix)
                logger.info(
                    f"Dry run: {len(xs_to_fix)} cross sections have right_station=0 "
                    "in ineffective flow areas"
                )

            results.statistics = {
                'total_xs_in_file': len(xs_df_all),
                'xs_with_ineff_checked': results.total_xs_checked,
                'xs_fixed': results.total_xs_fixed
            }

        except Exception as e:
            logger.error(f"Failed to fix ineffective flow: {e}")
            raise

        return results

    @staticmethod
    @log_call
    def detect_ineffective_flow_issues(
        geom_path: Union[str, Path]
    ) -> FixResults:
        """
        Detect cross sections with malformed ineffective flow area data (dry run).

        Args:
            geom_path: Path to HEC-RAS geometry file.

        Returns:
            FixResults with messages for each cross section that would be fixed.
        """
        return RasFixit.fix_ineffective_flow(geom_path, backup=False, dry_run=True)

    # ========== MANNING'S N FIXES ==========

    @staticmethod
    @log_call
    def fix_mannings_n(
        geom_path: Union[str, Path],
        backup: bool = True,
        dry_run: bool = False,
        rs_list: Optional[List[str]] = None
    ) -> FixResults:
        """
        Fix Manning's n data for cross sections with missing or misaligned breakpoints.

        **Version upgrade fix (HEC-RAS 4.x → 6.x).** Not applicable to models
        originally created in HEC-RAS 6.x.

        Handles two categories of Manning's n errors common after HEC-RAS version
        upgrades (4.x to 6.x):

        1. **Missing data** (``#Mann= 0``): Reconstructs 3-breakpoint (LOB/MC/ROB)
           Manning's n using distance-weighted linear interpolation from the nearest
           upstream and downstream Type 1 cross sections that have valid data.

        2. **Misaligned breakpoints**: When RAS 6.6's version upgrade moved bank
           stations but left Manning's breakpoints at the old positions, snaps the
           MC and ROB breakpoints to the current bank station values.

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)
            backup: Create timestamped backup before modification (default True)
            dry_run: Detect issues without modifying file (default False)
            rs_list: Optional list of RS values to check. If None, checks all
                     Type 1 cross sections.

        Returns:
            FixResults with messages for each modified cross section.

        Raises:
            FileNotFoundError: If geometry file doesn't exist.

        Example:
            >>> results = RasFixit.fix_mannings_n("model.g01")
            >>> print(f"Fixed {results.total_xs_fixed} cross sections")

        Note:
            This fix targets models upgraded from HEC-RAS 4.x to 6.x where the
            version upgrade zeroed out or misaligned Manning's n breakpoints.
            All changes should be reviewed by a licensed professional engineer.
        """
        from ..geom.GeomCrossSection import GeomCrossSection
        import numpy as np
        import pandas as pd

        geom_path = Path(geom_path)
        if not geom_path.exists():
            raise FileNotFoundError(f"Geometry file not found: {geom_path}")

        results = FixResults()

        if backup and not dry_run:
            backup_path = RasFixit._create_backup(geom_path)
            results.backup_path = backup_path
            logger.info(f"Created backup: {backup_path}")

        try:
            xs_df = GeomCrossSection.get_cross_sections(geom_path)
            xs_type1 = xs_df[xs_df['Type'] == 1].copy()
            xs_type1['RS_num'] = xs_type1['RS'].str.strip().astype(float)
            xs_type1 = xs_type1.sort_values('RS_num', ascending=False).reset_index(drop=True)

            if rs_list is not None:
                rs_set = set(str(r).strip() for r in rs_list)
                check_df = xs_type1[xs_type1['RS'].apply(lambda x: str(x).strip() in rs_set)]
            else:
                check_df = xs_type1

            results.total_xs_checked = len(check_df)
            xs_to_fix = []

            def _extract_lob_mc_rob(mann_df):
                """Extract LOB/MC/ROB n-values from a Manning's DataFrame."""
                if mann_df is None or len(mann_df) == 0:
                    return None
                if 'Subsection' in mann_df.columns:
                    lob = mann_df[mann_df['Subsection'] == 'LOB']
                    mc = mann_df[mann_df['Subsection'] == 'Channel']
                    rob = mann_df[mann_df['Subsection'] == 'ROB']
                    lob_n = lob['n_value'].iloc[0] if len(lob) > 0 else mann_df.iloc[0]['n_value']
                    mc_n = mc['n_value'].iloc[0] if len(mc) > 0 else mann_df.iloc[1]['n_value'] if len(mann_df) > 1 else lob_n
                    rob_n = rob['n_value'].iloc[0] if len(rob) > 0 else mann_df.iloc[-1]['n_value']
                else:
                    lob_n = mann_df.iloc[0]['n_value']
                    mc_n = mann_df.iloc[1]['n_value'] if len(mann_df) > 1 else lob_n
                    rob_n = mann_df.iloc[-1]['n_value']
                return lob_n, mc_n, rob_n

            def _find_neighbor_with_mann(idx, direction):
                """Find nearest Type 1 XS with valid Manning's data."""
                step = -1 if direction == 'upstream' else 1
                k = idx + step
                while 0 <= k < len(xs_type1):
                    row = xs_type1.iloc[k]
                    r, rch, rs_val = row['River'], row['Reach'], str(row['RS'])
                    try:
                        m = GeomCrossSection.get_mannings_n(
                            geom_path, r, rch, rs_val
                        )
                        if m is not None and len(m) > 0:
                            return row, m
                    except Exception:
                        pass
                    k += step
                return None, None

            for _, row in check_df.iterrows():
                river = row['River']
                reach = row['Reach']
                rs = str(row['RS'])
                rs_num = float(rs.strip())
                idx = xs_type1.index[xs_type1['RS_num'] == rs_num].tolist()
                if not idx:
                    continue
                idx = idx[0]

                try:
                    banks = GeomCrossSection.get_bank_stations(
                        geom_path, river, reach, rs
                    )
                    if banks is None:
                        continue
                    bank_left, bank_right = banks

                    mann = GeomCrossSection.get_mannings_n(
                        geom_path, river, reach, rs
                    )

                    if mann is None or len(mann) == 0:
                        # Category A: Missing data — reconstruct from neighbors
                        up_row, up_mann = _find_neighbor_with_mann(idx, 'upstream')
                        dn_row, dn_mann = _find_neighbor_with_mann(idx, 'downstream')

                        if up_mann is None or dn_mann is None:
                            logger.warning(
                                f"Cannot interpolate Mann for RS {rs}: "
                                f"missing {'upstream' if up_mann is None else 'downstream'} neighbor"
                            )
                            continue

                        up_vals = _extract_lob_mc_rob(up_mann)
                        dn_vals = _extract_lob_mc_rob(dn_mann)
                        if up_vals is None or dn_vals is None:
                            continue

                        up_rs = float(str(up_row['RS']).strip())
                        dn_rs = float(str(dn_row['RS']).strip())
                        dist_ue = up_rs - rs_num
                        dist_ed = rs_num - dn_rs

                        if dist_ue + dist_ed <= 0:
                            continue

                        w_u = dist_ed / (dist_ue + dist_ed)
                        w_d = dist_ue / (dist_ue + dist_ed)

                        lob_n = round(w_u * up_vals[0] + w_d * dn_vals[0], 4)
                        mc_n = round(w_u * up_vals[1] + w_d * dn_vals[1], 4)
                        rob_n = round(w_u * up_vals[2] + w_d * dn_vals[2], 4)

                        # LOB breakpoint = leftmost sta/elev station
                        sta_elev = GeomCrossSection.get_station_elevation(
                            geom_path, river, reach, rs
                        )
                        lob_sta = float(sta_elev['Station'].min())

                        new_mann = pd.DataFrame({
                            'Station': [lob_sta, bank_left, bank_right],
                            'n_value': [lob_n, mc_n, rob_n]
                        })

                        msg = FixMessage(
                            message_id="FX_MN_01",
                            fix_type="MANNINGS_N",
                            river=river,
                            reach=reach,
                            station=rs,
                            action=FixAction.MANNINGS_N_REWRITTEN,
                            message=(
                                f"Reconstructed from neighbors: "
                                f"LOB={lob_n:.3f} (U:{up_vals[0]:.3f}/D:{dn_vals[0]:.3f}), "
                                f"MC={mc_n:.3f} (U:{up_vals[1]:.3f}/D:{dn_vals[1]:.3f}), "
                                f"ROB={rob_n:.3f} (U:{up_vals[2]:.3f}/D:{dn_vals[2]:.3f}). "
                                f"Weights: U={w_u:.3f}, D={w_d:.3f}"
                            )
                        )
                        results.messages.append(msg)
                        xs_to_fix.append((river, reach, rs, new_mann))

                    elif len(mann) >= 3:
                        # Check if breakpoints match bank stations
                        mann_stations = mann['Station'].values
                        # MC breakpoint should be at left bank
                        mc_diff = abs(mann_stations[1] - bank_left)
                        # ROB breakpoint should be at right bank
                        rob_diff = abs(mann_stations[-1] - bank_right)

                        if mc_diff > 0.01 or rob_diff > 0.01:
                            # Category B: Misaligned — snap to banks
                            new_mann = pd.DataFrame({
                                'Station': [mann_stations[0], bank_left, bank_right],
                                'n_value': [
                                    mann.iloc[0]['n_value'],
                                    mann.iloc[1]['n_value'],
                                    mann.iloc[-1]['n_value']
                                ]
                            })

                            msg = FixMessage(
                                message_id="FX_MN_02",
                                fix_type="MANNINGS_N",
                                river=river,
                                reach=reach,
                                station=rs,
                                action=FixAction.MANNINGS_N_REWRITTEN,
                                message=(
                                    f"Snapped breakpoints to banks: "
                                    f"MC {mann_stations[1]:.2f}->{bank_left:.2f} "
                                    f"(diff={mc_diff:.2f}), "
                                    f"ROB {mann_stations[-1]:.2f}->{bank_right:.2f} "
                                    f"(diff={rob_diff:.2f})"
                                )
                            )
                            results.messages.append(msg)
                            xs_to_fix.append((river, reach, rs, new_mann))

                except Exception as e:
                    logger.warning(f"Error checking {river}/{reach}/RS {rs}: {e}")
                    continue

            if not dry_run and xs_to_fix:
                for river, reach, rs, new_mann in xs_to_fix:
                    try:
                        GeomCrossSection.set_mannings_n(
                            geom_path, river, reach, rs, new_mann,
                            format_flag=0, change_flag=0
                        )
                        results.total_xs_fixed += 1
                        logger.debug(f"Fixed Manning's n for {river}/{reach}/RS {rs}")
                    except Exception as e:
                        logger.error(f"Failed to fix {river}/{reach}/RS {rs}: {e}")

            elif dry_run:
                results.total_xs_fixed = len(xs_to_fix)
                logger.info(
                    f"Dry run: {len(xs_to_fix)} cross sections need Manning's n fixes"
                )

            results.statistics = {
                'xs_checked': results.total_xs_checked,
                'xs_fixed': results.total_xs_fixed,
                'reconstructed': len([m for m in results.messages if m.message_id == "FX_MN_01"]),
                'realigned': len([m for m in results.messages if m.message_id == "FX_MN_02"])
            }

        except Exception as e:
            logger.error(f"Failed to fix Manning's n: {e}")
            raise

        return results

    @staticmethod
    @log_call
    def detect_mannings_n_issues(
        geom_path: Union[str, Path]
    ) -> FixResults:
        """
        Detect Manning's n issues without modifying the file (dry run).

        Args:
            geom_path: Path to HEC-RAS geometry file (.g##)

        Returns:
            FixResults with messages for each cross section that would be fixed.
        """
        return RasFixit.fix_mannings_n(geom_path, backup=False, dry_run=True)
